export const ERROR_CODE = {
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const

export const ERROR_MESSAGE = {
  PRODUCT_NOT_FOUND: 'Product not found',
  UNEXPECTED_ERROR: 'Unexpected error',
  VALIDATED_REQUEST_DATA_IS_MISSING: 'Validated request data is missing',
} as const
